CXX = clang++
CXXFLAGS = -std=c++1y -stdlib=libc++
LDFLAGS = -std=c++1y -stdlib=libc++ -lc++abi
TESTOBJS = huffman_tree.o decoder.o encoder.o binary_file_reader.o binary_file_writer.o frequency.o
include Makefile.proxy
