CXX = clang++
CXXFLAGS = -std=c++1y -stdlib=libc++
LDFLAGS = -std=c++1y -stdlib=libc++ -lc++abi
TESTOBJS = anagram_dict.o fib.o pronounce_dict.o cartalk_puzzle.o common_words.o
include Makefile.proxy
